### ISSUE TITLE
게시글 리스트 조회 API 버그

### ISSUE THREAD

**Issue by a-ryang** [MBTI-Channel/server#166]
## 개요
- 게시글 조회 API 요청시, 500 에러 발생
## Log
```ts
2022-08-18 17:26:19 error: TypeError: Cannot read properties of undefined (reading 'id') 
 TypeError: Cannot read properties of undefined (reading 'id')
    at PostService.<anonymous> (/Users/chw/work/mbti-channel/server/src/modules/post/post.service.ts:302:52)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/chw/work/mbti-channel/server/src/modules/post/post.service.ts:17:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
2022-08-18 17:26:19 info: ::1 - - [18/Aug/2022:08:26:19 +0000] "GET /posts?category=trip HTTP/1.1" 500 29 "-" "PostmanRuntime/7.29.2"
```
## Code
- PostService.getAll
- line 302
```ts
public async getAll() {

    // 배열 마지막 id를 nextId에 할당
    const nextId = postArray[postArray.length - 1].id; // TypeError: Cannot read properties of undefined (reading 'id')

}
```
## Tasks

- [x] 게시글 리스트 조회
- [x] 대댓글 리스트 조회

> 🚧 추가로 발견되는게 있다면 Tasks에 추가해주세요

**Comment by a-ryang** [comment]
post 테이블이 비어있을때, line 289, 295에 다음 두 함수가 빈 배열을 return함
```ts
this._postRepository.findAllPostsWithMbti
this._postRepository.findAllPosts
```

```ts
const nextId = postArray[postArray.length - 1].id; // postArray는 빈 배열이므로

const nextId = [].id; // 에러 발생
```

**Comment by a-ryang** [comment]
대댓글 조회도 동일한 문제 발생하여 수정 필요
